name: Publish to npm with Semantic Release

on:
  push:
    branches:
      - master
      - next # For pre-releases

jobs:
  release:
    name: Publish Semantic Release
    runs-on: ubuntu-latest

    permissions:
      contents: write # Needed to create releases and tags
      issues: write # Needed to comment on issues
      pull-requests: write # Needed to comment on pull requests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for semantic-release to access all commit history

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build the project
        run: pnpm build

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # For publishing to npm
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For creating releases and commenting
        run: pnpx semantic-release
